spring.application.name=product-api


spring.cloud.stream.bindings.commands-out-0.destination=products.commands
spring.cloud.stream.bindings.commands-out-0.contentType=application/json

spring.cloud.function.definition=handleReplies
spring.cloud.stream.bindings.handleReplies-in-0.destination=products.replies
spring.cloud.stream.bindings.handleReplies-in-0.contentType=application/json
spring.cloud.stream.bindings.handleReplies-in-0.group=product-api-group
spring.cloud.stream.bindings.handleReplies-in-0.consumer.startOffset=latest

spring.cloud.stream.kafka.binder.brokers=localhost:9092
